### ISSUE TITLE
The image from readme is broken.

### ISSUE THREAD

**Issue by Heimdell** [MaiaVictor/abstract-algorithm#1]
![it](https://github.com/MaiaVictor/abstract-algorithm/blob/master/images/combinators_rules.png) loads only few of rows. I'm interested to see full image.

**Comment by MaiaVictor** [comment]
How so? I see the full image here. That's the whole thing. Anyway, you can see that image on the original paper introducing interaction combinators (and Mazza's paper introducing symmetric interaction combinators).

**Comment by lukaszlew** [comment]
I see the image broken as well.
https://github.com/MaiaVictor/abstract-algorithm/blob/master/images/combinators_rules.png

**Comment by lukaszlew** [comment]
It is fixed now, you can close the issue.
