### ISSUE TITLE
Is it possible to expand AL to include low level commands?

### ISSUE THREAD

**Issue by Josef-Vonasek** [MaiaVictor/abstract-algorithm#7]
Is it possible to create `node` that calls native & impure functions like `IO`, `integer / float arithmetic`, `FFI`, `...` ?

**Comment by MaiaVictor** [comment]
Yes, there are some papers on how to do similar things, and Anton Salikhmetov does that on [his repository](https://github.com/codedot/lambda). He has many other implementations, not just the abstract one. You may want to ask him. I never attempted to do that, but I believe that, for IO, it would be just a matter of adding new node types and triggering the IO actions. For arithmetic, just add node types for containing ints, and with reduction rules that add/mul/div them.

But note that having side-effects may bloat the algorithm. If you are implementing it in an asic, on the gpu, or somewhere else, you want it to be as simple as possible. If you have a lot of code that compiles to a modified version of interaction nets (with IO etc), your code may be ASIC incompatible. So, for IO, my preferred plan is to reduce interaction nets purely, then return a datatype describing the IO actions you want to perform. Then you perform those actions by interpreting that data in a host language. That way, the hard work happens on unmodified interaction nets, and you use a host language as a bridge with real world stuff.

**Comment by Josef-Vonasek** [comment]
Thanks - Yeah, I believe support for native arithmetic is the thing I really care about. Other stuff is mostly OS related so there is no reason to have it built right into the net.
